name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge_group:
    types: [ checks_requested ]
permissions:
  contents: read
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        # Keep this list as: all supported LTS JDKs, the latest GA JDK, and optionally the latest EA JDK (if available).
        # https://www.oracle.com/java/technologies/java-se-support-roadmap.html
        java: [ 11, 17, 21, 23 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B verify
      - name: Build with Maven (-Dquickly)
        run: mvn -B clean verify -Dquickly
      - name: Build with Maven (-Popenshift)
        run: mvn -B -e -Popenshift -DskipTests clean package
