name: Conventional Commits
on:
  pull_request:
    branches:
      - '*'
permissions:
  contents: read
jobs:
  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Verify Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0
