name: Maven

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge_group:
    types:
      - checks_requested

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        java:
          - 25

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDKs
        uses: actions/setup-java@v5
        with:
          # Keep this list as: all supported LTS JDKs, the latest GA JDK, and optionally the latest EA JDK (if available).
          # Reference: https://adoptium.net/support/
          java-version: |
            17
            21
            25
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: ./mvnw --batch-mode --no-transfer-progress --activate-profiles lts verify

      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: ${{ matrix.os }}-${{ matrix.java }}-test-reports
          path: |
            **/surefire-reports*/*
            **/failsafe-reports*/*
